console.log("aaaaaaaaaaaaaaaaaa");
console.log("         a       a");
console.log("         a       a");
console.log("         a       a");
console.log("         a       a");
console.log("aaaaaaaaaaaaaaaaaa");
console.log("jjjjjjjjj");
console.log("j");
console.log("j");
console.log("j");
console.log("j");
console.log("jjjjjjjjjjjjjjjjjj");